apiVersion: batch/v1
kind: Job
metadata:
  name: handson-job
spec:
  completions: 6
  parallelism: 2
  template:
    spec:
      containers:
      - name: handson-job
        image: ubuntu:24.04
        command: ["echo"]
        args: ["Welcome To the CND Hands On Event!!"]
      restartPolicy: Never
