apiVersion: v1
kind: Service
metadata:
  labels:
    app: task
  name: task
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: task
